### ISSUE TITLE
plugin produces uncompilable code for if statement with comment

### ISSUE THREAD

**Issue by christophsturm** [personio/kotlin-auto-formatter#2]
in my project https://github.com/christophsturm/r2dbcfun

this code: 
```
                if (parameter.name != "id" // Primary key can be a pk class which is currently not handled here
                    && !supportedJavaTypes.contains(clazz)
                )
```
is converted to this, which does not compile, because it joins the comment with the beginning of the next line
```
                if (parameter.name != "id"
                    // Primary key can be a pk class which is currently not handled here &&
                    !supportedJavaTypes.contains(clazz)
                )
```

**Comment by hovinen** [comment]
Thanks for reporting this! I just committed a fix and will make a new release with the fix this evening.

**Comment by christophsturm** [comment]
thanks it works now. but i wonder if it wouldnt be better to keep the comment in the same line
now it looks like this: 
```
                if (parameter.name != "id"
                    // Primary key can be a pk class which is currently not handled here
                    && !supportedJavaTypes.contains(clazz)
```

and so the comment looks like it applies to the line after it, not before it. 
or maybe the comment should be moved before the code line:
```
                if (// Primary key can be a pk class which is currently not handled here
                    parameter.name != "id"
                    && !supportedJavaTypes.contains(clazz)
```

**Comment by hovinen** [comment]
In this case, it inserts a line break before the comment in order to maintain the 100 column limit. If the comment fit within that limit, it would keep it on the same line.

Moving the comment to be prior to the operand would be quite complicated to get right, I think. Right now the formatter mostly only adjusts whitespace and inserts line breaks, only rearranging things in a few specific cases.

I suggest adjusting cases like this manually as needed.
