### ISSUE TITLE
Re/dual license under Apache 2

### ISSUE THREAD

**Issue by fcurts** [personio/kotlin-auto-formatter#23]
Legal departments go bananas whenever they hear "GPL".
Arguing "it's LGPL" or "it's only a tool" often doesn't make a difference.

Re-licensing or dual-licensing this project under Apache 2 (same as Kotlin itself) would make it far easier to adopt.

**Comment by hovinen** [comment]
Thanks for the explanation.

The decision to use LGPL instead of Apache was an informed one, with the intention that using the tool in any other project -- regardless of that project's license -- is perfectly fine. Only changes to the formatter itself must remain under the same license. Absent any specific legal concern with the existing license, I see no justification for changing it.

I'm closing this for now. Feel free to reopen it if you or your legal department can cite any concrete concern justifying a change in license.

**Comment by fcurts** [comment]
Obviously your call, but putting a tool for an Apache licensed language/ecosystem under LGPL will cost you a lot of users. Good luck!
